#!/bin/sh

# add_fix &
sxhkd &
pkill polybar
polybar my_bar &
bspc desktop -l tiled
# picom -b --experimental-backends &
nitrogen --restore &

bspc monitor -d 1 2 3

bspc config automatic_scheme            alternate
bspc config single_monocle              false
bspc config removal_adjustment          false
bspc config pointer_motion_interval     15

bspc config border_width                2
bspc config window_gap                  9
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true

bspc config focused_border_color        '#3EE3E6'
bspc config normal_border_color         '#707070'

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true


bspc rule -a Zathura state=tiled
bspc rule -a mpv state=tiled
bspc rule -a Emacs state=tiled
