#!/bin/sh

# add_fix &
pkill sxhkd
sxhkd &
pkill polybar
polybar my_bar &
bspc desktop -l tiled
# picom -b --experimental-backends &
nitrogen --restore &

bspc monitor -d 1 2 3 4

bspc config automatic_scheme            alternate
bspc config removal_adjustment          true

bspc config border_width                3
bspc config window_gap                  7
bspc config focus_follows_pointer       true
bspc config pointer_follows_focus         true
bspc config history_aware_focus         true

bspc config focused_border_color        '#45f7e9'
bspc config normal_border_color         '#707070'

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config top_monocle_padding         -31


bspc rule -a Zathura state=tiled
bspc rule -a mpv state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a kitty_floating state=floating sticky=on rectangle=1200x700+2+2 center=on

# kitty --class kitty_floating
