#! /bin/sh

sxhkd &
killall polybar; polybar my_bar &
nitrogen --restore &

bspc monitor -d 1 2 3

bspc config border_width                2
bspc config window_gap                  9
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true

bspc config focused_border_color        '#3EE3E6'
bspc config normal_border_color         '#707070'

bspc config split_ratio                 0.58
bspc config single_monocle              true
bspc config borderless_monocle          true
bspc config gapless_monocle             true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a firefox desktop='^1'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
