#!/bin/bash

## Created By Aditya Shakya

MENU="$(rofi -sep "|" -dmenu -i -p 'System'  -width 15 -hide-scrollbar -line-padding 4 -padding 20 -lines 4 <<< "> Lock|> Logout|> Reboot|> Shutdown")"
            case "$MENU" in
                *Lock)      i3lock-fancy -t `xkblayout`;;
                *Logout)    bspc quit;;
                *Reboot)    reboot ;;
                *Shutdown)  shutdown now;;
            esac
