swipe:
  3:
    left:
      sendkey: 'LEFTCTRL+LEFTSHIFT+TAB' # history back
    right:
      sendkey: 'LEFTCTRL+TAB' # History back
    up:
        sendkey: 'LEFTCTRL+LEFTSHIFT+t'
    down:
        sendkey: 'LEFTCTRL+w'



tap:
    1:
        command: 'xdotool click 1'
    2:
        command: 'xdotool click 2'
    3:
        sendkey: 'LEFTMETA+space'

pinch:
    in:
        sendkey: 'LEFTMETA+f'
    out:
        sendkey: 'LEFTMETA+f'

threshold:
    swipe: 0.4
    tap: 0.1

interval:
  swipe: 0.6
  pinch: 0.1
  tap: 0.1

plugin: 
  inputs:
    libinput_command_input:
      enable-tap: true
      verbose: true
